MARP-3987 test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -211,14 +211,21 @@ jobs:
         curl --fail --location --retry 3 --retry-delay 5 --output cspell.json "${{ inputs.cspellConfigUrl }}"
 
     - name: Append extra cspell words
-      if: inputs.cspellExtraWords != ''
       run: |
         FILE="${{ inputs.cspellExtraWords }}"
+        DEFAULT_FILE=".github/cspell-extra-words.txt"
 
         if [ ! -f "$FILE" ]; then
-          echo "Extra cspell words file not found: $FILE"
-          exit 1
+          if [ "$FILE" = "$DEFAULT_FILE" ]; then
+            echo "Default extra words file not found ($FILE). Skipping..."
+            exit 0
+          else
+            echo "Custom extra words file not found: $FILE"
+            exit 1
+          fi
         fi
+
+        echo "Appending extra words from $FILE"
 
         jq --arg words "$(cat "$FILE")" '
           .words += (
