MARP-620 Update release drafter workflow with multiple options (#37)

diff --git a/.github/workflows/release-drafter.yml b/.github/workflows/release-drafter.yml
--- a/.github/workflows/release-drafter.yml
+++ b/.github/workflows/release-drafter.yml
@@ -1,17 +1,17 @@
-name: Release Drafter
+name: Reusable Release Drafter
 
 on:
-  push:
-    # branches to consider in the event; optional, defaults to all
-    branches:
-      - master
-  # pull_request event is required only for autolabeler
-  pull_request:
-    # Only following types are handled by the action, but one can default to all as well
-    types: [opened, reopened, synchronize]
-  # pull_request_target event is required for autolabeler to support PRs from forks
-  # pull_request_target:
-  #   types: [opened, reopened, synchronize]
+  workflow_call:
+    inputs:
+      version:
+        description: 'Release version'
+        required: false
+        type: string
+      prerelease:
+        description: 'Is this a prerelease?'
+        required: false
+        default: 'false'
+        type: string
 
 permissions:
   contents: read
@@ -19,23 +19,41 @@ permissions:
 jobs:
   update_release_draft:
     permissions:
-      # write permission is required to create a github release
       contents: write
-      # write permission is required for autolabeler
-      # otherwise, read permission is required at least
       pull-requests: write
+    env:
+      IS_PUSH_EVENT_TRIGGERED: ${{ github.event_name == 'push' }}
+      COMMITISH: 'master'
     runs-on: ubuntu-latest
     steps:
-      # (Optional) GitHub Enterprise requires GHE_HOST variable set
-      #- name: Set GHE_HOST
-      #  run: |
-      #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV
+      - name: Checkout code
+        if: env.IS_PUSH_EVENT_TRIGGERED == 'false'
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-      # Drafts your next Release notes as Pull Requests are merged into "master"
+      - name: Get commit SHA for the provided version
+        id: get-sha
+        if: env.IS_PUSH_EVENT_TRIGGERED == 'false'
+        run: |
+          # Attempt to fetch the SHA for the provided version tag
+          SHA=$(git rev-list -n 1 ${{ github.event.inputs.version }} || echo "")
+          
+          # If SHA is empty, fallback to master branch
+          if [ -z "$SHA" ]; then
+            echo "Could not find SHA for the provided version. Falling back to master."
+            SHA="master"
+          fi
+          echo "COMMITISH=$SHA" >> $GITHUB_ENV
+
+      - name: Set commitish for push
+        if: env.IS_PUSH_EVENT_TRIGGERED == 'true'
+        run: echo "COMMITISH=master" >> $GITHUB_ENV
+      
       - uses: release-drafter/release-drafter@v6
-        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
-        # with:
-        #   config-name: my-config.yml
-        #   disable-autolabeler: true
+        with:
+          version: ${{ github.event.inputs.version }}
+          prerelease: ${{ github.event.inputs.prerelease }}
+          commitish: ${{ env.COMMITISH }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
